fix: Made board clickable to show x's & o's
hyperxtend/TicTacReact pull request #26
Opened 2020-05-27 06:58 UTC by hyperxtend

2020-05-28 13:09 UTC, strange-developer requested changes
Update `game.test.jsx` to `component.test.jsx`

2020-05-28 13:09 UTC, strange-developer commented on src/components/game/component.jsx
> +const Game = ({ history, moveNumber, onClick }) => {
Add some unit tests for this component

2020-05-28 13:13 UTC, hyperxtend commented on src/components/game/component.jsx
> +const Game = ({ history, moveNumber, onClick }) => {
Will do

2020-06-01 08:53 UTC, strange-developer requested changes

2020-06-01 08:53 UTC, strange-developer commented on src/components/game/component.test.jsx
> +    console.log('Button9: ', wrapper.find('button.square').at(8).html());
These console.log's can be removed

2020-06-01 08:53 UTC, strange-developer commented on src/components/game/component.test.jsx
> +import Game from './component';
These imports can come one after the other

2020-06-01 08:53 UTC, strange-developer commented on src/components/game/component.test.jsx
> +    board = shallow(<Board />);
The `Board` component should exist after shallow rendering the `Game` component. The tests within this `describe` block can actually be removed because the tests in a lower `describe` block cover these tests.

2020-06-01 08:53 UTC, strange-developer commented on src/components/game/component.test.jsx
> +  const MOVE_VALUES_ONE = ['X', '', '', '', '', '', '', '', ''];
Why are these variables in capital snake case?

2020-06-01 10:41 UTC, hyperxtend commented on src/components/game/component.test.jsx
> +  const MOVE_VALUES_ONE = ['X', '', '', '', '', '', '', '', ''];
I was using that case to differentiate between test data while I was playing around with the testing I change it

2020-06-02 07:31 UTC, strange-developer approved these changes

2020-06-02 07:31 UTC, merged