fix: Added navbar that uses react-router-dom
hyperxtend/TicTacReact pull request #32
Opened 2020-07-06 13:24 UTC by hyperxtend

2020-07-08 07:28 UTC, strange-developer requested changes

2020-07-08 07:28 UTC, strange-developer commented on src/index.jsx
> +        <Route path="/ScoreBoard" />
These route paths are duplicated in the NavBar component file. Perhaps create a shared space for these values.

2020-07-08 07:28 UTC, strange-developer commented on src/components/nav-bar/component.jsx
> +      pageName="/HomePage"
This prop doesn't refer to a `pageName`

2020-07-08 07:28 UTC, strange-developer commented on src/components/nav-bar/component.test.jsx
> +    expect(component.exists()).toBe(true);
You can add qa tags to each route and test that the URL for each `NavbarLink` is correct rather than testing the existence of the component only.

2020-07-13 06:54 UTC, strange-developer requested changes

2020-07-13 06:54 UTC, strange-developer commented on src/components/nav-bar/component.jsx
> +export const ScoreBoard = '/ScoreBoard';
These variable names should be upper snake case

2020-07-13 06:54 UTC, strange-developer commented on src/components/nav-bar/component.jsx
> +  <Navbar className="navigationBar">
`kebab-case` the class names

2020-07-13 06:54 UTC, strange-developer commented on src/components/verse-player/component.jsx
> +const VersePlayer = ({
I don't think `verse` is the correct word

2020-07-13 06:54 UTC, strange-developer commented on src/components/verse-player/component.jsx
> +    <div className="playerMoves">
kebab-case for class names

2020-07-14 06:47 UTC, strange-developer commented on src/index.jsx
> +        <Route path="/ScoreBoard" />
Still duplicated

2020-07-14 06:48 UTC, strange-developer commented on src/index.jsx
> +        <Route path="/ScoreBoard" />
Still duplicated in different places now

2020-07-14 07:02 UTC, strange-developer requested changes

2020-07-14 07:02 UTC, strange-developer commented on src/components/nav-bar/component.jsx
> +const NavbarLink = (props) => (
I don't think this needs to be a separate component. You can include it directly into the `NavigationBar` component.

2020-07-15 06:17 UTC, strange-developer requested changes

2020-07-15 06:17 UTC, strange-developer commented on src/components/game-for-2-players/component.jsx
> +const GameFor2Players = ({
Isn't the game only for two players?

2020-07-15 06:17 UTC, strange-developer commented on src/components/nav-bar/component.jsx
> +    ;
What are the semi colons for?

2020-07-15 06:29 UTC, hyperxtend commented on src/components/nav-bar/component.jsx
> +    ;
I forgot to remove them

2020-07-15 06:32 UTC, hyperxtend commented on src/components/game-for-2-players/component.jsx
> +const GameFor2Players = ({
Yes it's only for 2 players

2020-07-15 13:23 UTC, strange-developer approved these changes

2020-07-15 13:24 UTC, merged