Feature/play against computer
hyperxtend/TicTacReact pull request #34
Opened 2020-07-14 09:58 UTC by hyperxtend

2020-07-21 07:41 UTC, strange-developer requested changes

2020-07-21 07:41 UTC, strange-developer commented on src/pages/landing-page/component.test.jsx
> +    const descriptionSubHeader = component.find('h3').children().first().text();
Prefer QA tags

2020-07-21 07:41 UTC, strange-developer commented on src/pages/landing-page/component.test.jsx
> +  const component = shallow(<LandingPage />);
Change this variable name to wrapper

2020-07-21 07:41 UTC, strange-developer commented on src/pages/landing-page/component.test.jsx
> +    const descriptionSubHeader = component.find('h5').children().first().text();
Prefer QA tags

2020-07-21 07:41 UTC, strange-developer commented on src/pages/landing-page/menu-selection/component.test.jsx
> +  const component = shallow(<MenuSelection />);
Change variable name to wrapper

2020-07-21 07:41 UTC, strange-developer commented on src/pages/landing-page/menu-selection/component.test.jsx
> +    const menuHeader = component
Prefer QA tags

2020-07-21 07:41 UTC, strange-developer commented on src/pages/play-against-computer/component.css
> +  width: 30vw;
This component will need to be tested on different resolutions

2020-07-21 07:41 UTC, strange-developer commented on src/pages/play-against-computer/component.test.jsx
> +    const nextPlayer = wrapper
Prefer QA tags

2020-07-21 07:41 UTC, strange-developer commented on src/pages/play-against-computer/controller.js
> +  return `Next player is ${xIsNext ? 'X' : 'O'}`;
Turn this into an `if...else if...else`

2020-07-21 07:41 UTC, strange-developer commented on src/pages/play-against-computer/controller.test.js
> +
No need to leave lines in between the array elements

2020-07-21 07:41 UTC, strange-developer commented on src/reducers/state-of-game/reducer.test.js
> +        undefined,
Is `undefined` in the expectation correct?

2020-07-21 07:41 UTC, strange-developer commented on src/routes/component.test.jsx
> +    expect(wrapper.find(LandingPage)).toHaveLength(0);
This doesn't look like a correct test. We can rather test that each route exists.

2020-07-21 09:39 UTC, hyperxtend commented on src/reducers/state-of-game/reducer.test.js
> +        undefined,
Yes cause the last array of the current moves isn't added to history until the next move is played

2020-07-22 13:43 UTC, strange-developer commented on src/pages/play-against-computer/component.test.jsx
> +    const nextPlayer = wrapper
Here

2020-07-23 06:32 UTC, hyperxtend commented on src/reducers/state-of-game/reducer.test.js
> +        undefined,
Updated these tests

2020-07-23 08:58 UTC, strange-developer approved these changes

2020-07-23 08:58 UTC, merged