Fix: Updated project dependencies
hyperxtend/TicTacReact pull request #8
Opened 2020-04-01 13:52 UTC by hyperxtend

2020-04-01 14:05 UTC, hyperxtend reviewed
Fix: Dependencies updated

2020-04-02 11:19 UTC, strange-developer requested changes

2020-04-02 11:19 UTC, strange-developer commented on package.json
> +    "gh-pages": "^2.2.0",
`react-test-renderer` needs to be moved as well. It's not allowing me to comment on that line

2020-04-03 07:56 UTC, strange-developer approved these changes

2020-04-03 07:57 UTC, merged